// Google Form Attendance Importer — preview-first, code-aware.
(() => {
  if (typeof Teacher === 'undefined') return;
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
  const sig=v=>norm(v).split(' ').filter(Boolean).filter(x=>x.length>1);
  function csv(text){const out=[];let r=[],c='',q=false;for(let i=0;i<text.length;i++){const x=text[i],n=text[i+1];if(x==='"'&&q&&n==='"'){c+='"';i++;}else if(x==='"')q=!q;else if(x===','&&!q){r.push(c);c='';}else if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&n==='\n')i++;r.push(c);if(r.some(v=>String(v).trim()))out.push(r);r=[];c='';}else c+=x;}r.push(c);if(r.some(v=>String(v).trim()))out.push(r);return out;}
  function score(name,s){const q=sig(name), full=sig(`${s.first_name||''} ${s.middle_name||''} ${s.last_name||''}`), fl=sig(`${s.first_name||''} ${s.last_name||''}`), last=sig(s.last_name||'');if(!q.length||!last.length)return 0;const sorted=a=>[...a].sort().join('|');if(sorted(q)===sorted(full)||sorted(q)===sorted(fl))return 100;if(q.join('|')===last.join('|'))return 90;const o=q.filter(t=>full.includes(t)).length;if(o===q.length&&o>=2)return 80+Math.min(9,o);return 0;}
  function match(name,roster){const a=roster.map(s=>({s,n:score(name,s)})).filter(x=>x.n>=70).sort((a,b)=>b.n-a.n);if(!a.length)return{status:'unmatched'};const tied=a.filter(x=>x.n===a[0].n);if(tied.length>1)return{status:'review',candidates:tied.map(x=>x.s)};return{status:a[0].n>=90?'matched':'review',student:a[0].s,candidates:a.slice(0,4).map(x=>x.s)};}
  function inspect(matrix){const h=matrix[0].map(norm);const ni=h.findIndex(x=>x.includes('complete name')||x==='name'||x.includes('student name'));const ci=h.findIndex(x=>x.includes('attendance code'));const ti=h.findIndex(x=>x.includes('timestamp'));if(ni<0)throw new Error('Complete Name column not found.');const counts=new Map();matrix.slice(1).forEach(r=>{const code=String(ci>=0?r[ci]:'').trim();if(code)counts.set(code,(counts.get(code)||0)+1);});return{ni,ci,ti,codes:[...counts.entries()].sort((a,b)=>b[1]-a[1])};}

  Teacher.openAttendanceImport=async function(){const cid=Teacher.state.classId;if(!cid)return;const roster=await api('GET',`/classes/${cid}/roster`).catch(()=>[]);Teacher._attendanceImportRoster=Array.isArray(roster)?roster:[];const box=document.getElementById('teacher-tab-content');box.innerHTML=`<div class="space-y-4"><button onclick="Teacher.renderAttendance()" class="text-sm font-bold text-eduBlue-600"><i class="fa-solid fa-arrow-left mr-1"></i> Back to Attendance</button><div class="glass-card rounded-2xl p-5"><h4 class="font-black text-slate-800"><i class="fa-solid fa-file-import mr-2 text-emerald-600"></i>Import Google Form Attendance</h4><p class="mt-1 text-xs text-slate-500">Upload one complete Google Form CSV. The portal will detect its Attendance Codes. Timestamp remains reference-only.</p><label class="mt-4 block text-xs font-bold text-slate-600">Google Form CSV<input id="att-import-file" onchange="Teacher.detectAttendanceCodes()" type="file" accept=".csv,text/csv" class="mt-1 block w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5"></label><div id="att-code-controls" class="mt-4 hidden grid gap-4 md:grid-cols-2"><label class="text-xs font-bold text-slate-600">Attendance Code<select id="att-import-code" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"></select></label><label class="text-xs font-bold text-slate-600">Official Attendance Date<input id="att-import-date" type="date" class="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2.5"></label></div><div id="att-code-summary" class="mt-3"></div><label class="mt-4 flex items-center gap-2 text-xs text-slate-600"><input id="att-import-absent" type="checkbox"> Mark enrolled students with no accepted response as Absent (OFF by default)</label><button onclick="Teacher.previewAttendanceImport()" class="mt-5 rounded-xl bg-eduBlue-600 px-4 py-2.5 text-sm font-black text-white"><i class="fa-solid fa-magnifying-glass mr-1"></i> Preview Selected Attendance</button></div><div id="att-import-preview"></div></div>`;};

  Teacher.detectAttendanceCodes=async function(){try{const f=document.getElementById('att-import-file')?.files?.[0];if(!f)return;const matrix=csv(await f.text());const meta=inspect(matrix);Teacher._attendanceCSV={matrix,meta};const sel=document.getElementById('att-import-code');sel.innerHTML=meta.codes.map(([c,n])=>`<option value="${esc(c)}">${esc(c)} — ${n} response${n===1?'':'s'}</option>`).join('');document.getElementById('att-code-controls').classList.remove('hidden');document.getElementById('att-code-summary').innerHTML=`<div class="rounded-xl bg-blue-50 border border-blue-100 p-3 text-xs text-blue-800"><b>${meta.codes.length}</b> attendance code${meta.codes.length===1?'':'s'} detected from <b>${Math.max(0,matrix.length-1)}</b> response rows. Select one code and assign its official attendance date.</div>`;}catch(e){Toast.show('CSV Error',e.message||'Could not read CSV.','error');}};

  Teacher.previewAttendanceImport=async function(){const saved=Teacher._attendanceCSV,date=document.getElementById('att-import-date')?.value,code=document.getElementById('att-import-code')?.value;if(!saved||!date||!code)return Toast.show('Import Required','Upload the CSV, select an Attendance Code, and choose its official date.','error');const {matrix,meta}=saved,seenRaw=new Set(),seenStudent=new Set(),rows=[];matrix.slice(1).forEach((r,i)=>{const raw=String(r[meta.ni]||'').trim(),rc=String(meta.ci>=0?r[meta.ci]:'').trim();if(!raw||norm(rc)!==norm(code))return;const m=match(raw,Teacher._attendanceImportRoster||[]);let status=m.status,key=norm(raw);if(seenRaw.has(key)||(m.student&&seenStudent.has(String(m.student.id))))status='duplicate';seenRaw.add(key);if(m.student&&status!=='duplicate')seenStudent.add(String(m.student.id));rows.push({row:i+2,rawName:raw,code:rc,timestamp:meta.ti>=0?r[meta.ti]:'',status,student:m.student||null,candidates:m.candidates||[]});});Teacher._attendanceImport={date,code,rows};Teacher.renderAttendanceImportPreview();};

  Teacher.renderAttendanceImportPreview=function(){const box=document.getElementById('att-import-preview'),d=Teacher._attendanceImport;if(!box||!d)return;const count=s=>d.rows.filter(r=>r.status===s).length;box.innerHTML=`<div class="glass-card rounded-2xl p-5"><h5 class="font-black text-slate-800">${esc(d.code)} <span class="text-slate-400">•</span> ${esc(d.date)}</h5><div class="mt-3 flex flex-wrap gap-2 text-xs font-bold"><span class="rounded-full bg-emerald-100 px-3 py-1 text-emerald-700">${count('matched')} Matched</span><span class="rounded-full bg-amber-100 px-3 py-1 text-amber-700">${count('review')} Review</span><span class="rounded-full bg-red-100 px-3 py-1 text-red-700">${count('unmatched')} Unmatched</span><span class="rounded-full bg-slate-100 px-3 py-1 text-slate-600">${count('duplicate')} Duplicate</span></div><div class="mt-4 overflow-x-auto"><table class="gradebook w-full text-left text-xs"><thead><tr><th>Form Name</th><th>Timestamp</th><th>Portal Student</th><th>Status</th></tr></thead><tbody>${d.rows.map((r,i)=>`<tr><td>${esc(r.rawName)}</td><td>${esc(r.timestamp||'—')}</td><td>${['review','unmatched'].includes(r.status)?`<select onchange="Teacher.resolveAttendanceImport(${i},this.value)" class="rounded-lg border px-2 py-1"><option value="">Select student…</option>${(Teacher._attendanceImportRoster||[]).map(s=>`<option value="${esc(s.id)}">${esc(s.last_name)}, ${esc(s.first_name)}</option>`).join('')}</select>`:esc(r.student?`${r.student.last_name}, ${r.student.first_name}`:'—')}</td><td>${r.status==='matched'?'✅ Matched':r.status==='duplicate'?'⚪ Duplicate ignored':r.status==='review'?'⚠️ Review':'❌ Unmatched'}</td></tr>`).join('')}</tbody></table></div><p class="mt-4 text-xs text-slate-500">Only Matched rows are saved. Resolve Review/Unmatched rows before confirming. Duplicate responses count once.</p><button onclick="Teacher.confirmAttendanceImport()" class="mt-4 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-black text-white"><i class="fa-solid fa-check mr-1"></i> Confirm Import</button></div>`;};
  Teacher.resolveAttendanceImport=function(i,id){const r=Teacher._attendanceImport?.rows?.[i],s=(Teacher._attendanceImportRoster||[]).find(x=>String(x.id)===String(id));if(!r)return;r.student=s||null;r.status=s?'matched':'unmatched';Teacher.renderAttendanceImportPreview();};
  Teacher.confirmAttendanceImport=async function(){const d=Teacher._attendanceImport;if(!d)return;const matched=d.rows.filter(r=>r.status==='matched'&&r.student);if(!matched.length)return Toast.show('Nothing to Import','No matched students are ready.','error');if(!confirm(`Import ${d.code} attendance for ${matched.length} matched student${matched.length===1?'':'s'} on ${d.date}?`))return;try{const session=await api('POST','/attendance/sessions',{classId:Teacher.state.classId,sessionDate:d.date});for(const r of matched)await api('PUT',`/attendance/sessions/${session.id}/records/${r.student.id}`,{status:'present'});if(document.getElementById('att-import-absent')?.checked){const p=new Set(matched.map(r=>String(r.student.id)));for(const s of Teacher._attendanceImportRoster||[])if(!p.has(String(s.id)))await api('PUT',`/attendance/sessions/${session.id}/records/${s.id}`,{status:'absent'});}await api('POST',`/attendance/sessions/${session.id}/close`);Toast.show('Attendance Imported',`${matched.length} students recorded for ${d.code}.`,'success');Teacher._attendanceImport=null;await Teacher.renderAttendance();}catch(e){}};

  const original=Teacher.renderAttendance.bind(Teacher);Teacher.renderAttendance=async function(){await original();const box=document.getElementById('teacher-tab-content');if(!box||box.querySelector('[data-att-import]'))return;const h=[...box.querySelectorAll('h4')].find(x=>x.textContent.toLowerCase().includes('attendance'));if(!h)return;const b=document.createElement('button');b.type='button';b.dataset.attImport='true';b.className='rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-xs font-black text-emerald-700 hover:bg-emerald-100';b.innerHTML='<i class="fa-solid fa-file-import mr-1"></i> Import Google Form CSV';b.onclick=()=>Teacher.openAttendanceImport();(h.parentElement?.parentElement||h.parentElement)?.appendChild(b);};
})();