const express=require('express');
const XLSX=require('xlsx');
const {pool}=require('../db');
const {authenticate,requireRole,requireClassOwnership}=require('../middleware/auth');
const {computeClassGrade}=require('../utils/grading');
const router=express.Router();router.use(authenticate,requireRole('teacher','admin'));
function equivalent(value){const p=Number(value);if(!Number.isFinite(p))return {numeric:'—',remarks:'INC'};const whole=Math.max(0,Math.min(100,Math.round(p)));if(whole<70)return {numeric:'5.0',remarks:'INC'};return {numeric:(1+(100-whole)*0.1).toFixed(1),remarks:whole>=75?'Passed':'INC'};}
function safeName(v){return String(v||'Class').replace(/[\\/:*?"<>|]/g,'-').slice(0,80);}
router.get('/:classId/final-grades.xlsx',requireClassOwnership,async(req,res,next)=>{try{const {classId}=req.params;const cls=(await pool.query(`SELECT c.subject,c.section,c.year_level,c.room_number,t.academic_year,t.semester FROM classes c JOIN academic_terms t ON t.id=c.term_id WHERE c.id=$1`,[classId])).rows[0];if(!cls)return res.status(404).json({error:'Class not found.'});const roster=(await pool.query(`SELECT s.id,s.student_number,s.first_name,s.last_name FROM students s JOIN enrollments e ON e.student_id=s.id WHERE e.class_id=$1 AND e.status='active' ORDER BY s.last_name,s.first_name`,[classId])).rows;const computed=[];const componentNames=new Map();for(const s of roster){const g=await computeClassGrade(s.id,classId);for(const [key,c] of Object.entries(g.components||{}))componentNames.set(key,c.name||key);computed.push({s,g});}
 const headers=['Student Number','Student Name',...componentNames.values(),'Final Grade','Grade Equivalent','Remarks','Grade Status'];const data=[headers];for(const {s,g} of computed){const eq=equivalent(g.finalGrade);const row=[s.student_number,`${s.last_name}, ${s.first_name}`];for(const key of componentNames.keys()){const c=g.components?.[key];row.push(c&&Number.isFinite(Number(c.percent))?Math.round(Number(c.percent)*100)/100:'');}row.push(g.finalGrade==null?'':g.finalGrade,g.finalGrade==null?'':eq.numeric,g.finalGrade==null?'INC':eq.remarks,g.status||'in_progress');data.push(row);}
 const ws=XLSX.utils.aoa_to_sheet(data);ws['!cols']=headers.map((h,i)=>({wch:i===1?28:Math.max(14,String(h).length+2)}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Final Grades');const info=XLSX.utils.aoa_to_sheet([['Subject',cls.subject],['Section',cls.section],['Year Level',cls.year_level],['Room',cls.room_number||''],['Academic Year',cls.academic_year],['Semester',cls.semester]]);XLSX.utils.book_append_sheet(wb,info,'Class Information');const buffer=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});const filename=`${safeName(cls.subject)}-${safeName(cls.section)}-Final-Grades.xlsx`;res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.setHeader('Content-Disposition',`attachment; filename="${filename}"`);res.send(buffer);}catch(e){next(e);}});
module.exports=router;
