const express = require('express');
const crypto = require('crypto');
const { pool } = require('../db');
const { authenticate, requireRole, requireClassOwnership } = require('../middleware/auth');
const { audit } = require('../utils/audit');
const { computeClassGrade, buildAdjustmentContext, computeAdjustmentDelta } = require('../utils/grading');
const router = express.Router();
router.use(authenticate);
function checkStudentAccess(req, studentId){return req.user.role!=='student'||req.user.id===studentId;}

async function getClassGradebook(classId){
 const {rows:roster}=await pool.query(`SELECT s.id,s.student_number,s.first_name,s.last_name FROM students s JOIN enrollments e ON e.student_id=s.id WHERE e.class_id=$1 AND e.status='active' ORDER BY s.last_name,s.first_name`,[classId]);
 return Promise.all(roster.map(async s=>{
  const grade=await computeClassGrade(s.id,classId);const comps=grade.components||{};
  const dynamicComponents=Object.entries(comps).map(([key,c])=>({key,name:c.name||({attendance:'Attendance',quiz:'Quiz',performance:'Performance Task',exam:'Exam'}[key]||key),percent:c.percent,weight:Number(c.weight),available:!!c.available,adjusted:!!c.adjusted,earned:c.earned??null,max:c.max??null}));
  // Legacy fields remain for existing frontend compatibility. Dynamic/custom
  // components are additionally returned in components/componentOrder.
  return {studentId:s.id,studentNumber:s.student_number,studentName:`${s.last_name}, ${s.first_name}`,attendance:comps.attendance?.percent??null,quiz:comps.quiz?.percent??null,performance:comps.performance?.percent??null,exam:comps.exam?.percent??null,components:Object.fromEntries(dynamicComponents.map(c=>[c.key,c])),componentOrder:dynamicComponents.map(c=>c.key),finalGrade:grade.finalGrade,status:grade.status,incompleteReason:grade.message,schemeId:grade.schemeId||null,schemeVersion:grade.schemeVersion||null};
 }));
}

router.get('/:classId/students/:studentId',async(req,res,next)=>{try{const{classId,studentId}=req.params;if(!checkStudentAccess(req,studentId))return res.status(403).json({error:'You are not authorized to perform this action.'});if(req.user.role==='teacher'){const cls=(await pool.query('SELECT teacher_id FROM classes WHERE id=$1',[classId])).rows[0];if(!cls||cls.teacher_id!==req.user.id)return res.status(403).json({error:'You are not authorized to perform this action.'});}const result=await computeClassGrade(studentId,classId);if(req.user.role==='student'&&result.status!=='released')return res.json({...result,finalGrade:null,visibleToStudent:false});res.json({...result,visibleToStudent:true});}catch(e){next(e);}});
router.get('/:classId',requireClassOwnership,async(req,res,next)=>{try{res.json(await getClassGradebook(req.params.classId));}catch(e){next(e);}});
router.get('/:classId/gradebook',requireClassOwnership,async(req,res,next)=>{try{res.json(await getClassGradebook(req.params.classId));}catch(e){next(e);}});
router.post('/:classId/students/:studentId/finalize',requireRole('teacher','admin'),requireClassOwnership,async(req,res,next)=>{try{const{classId,studentId}=req.params;const result=await computeClassGrade(studentId,classId);if(!result.complete)return res.status(400).json({error:`Cannot finalize an incomplete grade. ${result.message}`});const prev=(await pool.query('SELECT status FROM grade_status WHERE student_id=$1 AND class_id=$2',[studentId,classId])).rows[0];await pool.query(`INSERT INTO grade_status(student_id,class_id,status,finalized_by,finalized_at) VALUES($1,$2,'finalized',$3,now()) ON CONFLICT(student_id,class_id) DO UPDATE SET status='finalized',finalized_by=excluded.finalized_by,finalized_at=excluded.finalized_at`,[studentId,classId,req.user.id]);await audit(req,{action:'grade_finalization',recordType:'grade_status',recordId:`${studentId}:${classId}`,previousValue:prev,newValue:'finalized'});res.json({message:'Grade finalized.'});}catch(e){next(e);}});
router.post('/:classId/students/:studentId/release',requireRole('teacher','admin'),requireClassOwnership,async(req,res,next)=>{try{const{classId,studentId}=req.params;const status=(await pool.query('SELECT status FROM grade_status WHERE student_id=$1 AND class_id=$2',[studentId,classId])).rows[0];if(!status||status.status!=='finalized')return res.status(400).json({error:'Grade must be finalized before it can be released.'});await pool.query(`UPDATE grade_status SET status='released',released_at=now() WHERE student_id=$1 AND class_id=$2`,[studentId,classId]);await audit(req,{action:'grade_release',recordType:'grade_status',recordId:`${studentId}:${classId}`});res.json({message:'Grade released to student.'});}catch(e){next(e);}});
router.post('/:classId/students/:studentId/reopen',requireRole('admin'),async(req,res,next)=>{try{const{classId,studentId}=req.params;const prev=(await pool.query('SELECT status FROM grade_status WHERE student_id=$1 AND class_id=$2',[studentId,classId])).rows[0];await pool.query(`UPDATE grade_status SET status='in_progress',finalized_by=NULL,finalized_at=NULL,released_at=NULL WHERE student_id=$1 AND class_id=$2`,[studentId,classId]);await audit(req,{action:'grade_reopen',recordType:'grade_status',recordId:`${studentId}:${classId}`,previousValue:prev,newValue:'in_progress'});res.json({message:'Grade reopened.'});}catch(e){next(e);}});
router.put('/:classId/students/:studentId/adjustments/:component',requireRole('teacher','admin'),requireClassOwnership,async(req,res,next)=>{try{const{classId,studentId,component}=req.params;if(!['attendance','quiz','performance','exam'].includes(component))return res.status(400).json({error:'Invalid component.'});const result=await computeAdjustmentDelta(studentId,classId,component,req.body.newTotal);if(!result.valid)return res.status(400).json({error:result.message});const existing=(await pool.query('SELECT * FROM grade_adjustments WHERE student_id=$1 AND class_id=$2 AND component=$3',[studentId,classId,component])).rows[0];const id=existing?.id||crypto.randomUUID();await pool.query(`INSERT INTO grade_adjustments(id,student_id,class_id,component,adjustment_points,reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(student_id,class_id,component) DO UPDATE SET adjustment_points=excluded.adjustment_points,reason=excluded.reason,created_by=excluded.created_by,updated_at=now()`,[id,studentId,classId,component,result.deltaPercent,req.body.reason||null,req.user.id]);await audit(req,{action:'grade_adjustment',recordType:'grade_adjustment',recordId:id,previousValue:existing||null,newValue:{...result,reason:req.body.reason||null}});res.json({message:'Grade adjustment saved.',...result});}catch(e){next(e);}});
module.exports=router;
