const express = require('express');
const crypto = require('crypto');
const { pool } = require('../db');
const { authenticate, requireRole, requireClassOwnership } = require('../middleware/auth');
const { audit } = require('../utils/audit');
const { computeClassGrade, buildAdjustmentContext, computeAdjustmentDelta } = require('../utils/grading');
const { getDynamicScheme, componentResult } = require('../utils/dynamic-grading');
const router = express.Router();
router.use(authenticate);
const VALID_COMPONENTS=['attendance','quiz','performance','exam'];
function checkStudentAccess(req,studentId){return req.user.role!=='student'||req.user.id===studentId;}
async function assertEnrolled(studentId,classId){const {rows}=await pool.query(`SELECT 1 FROM enrollments WHERE student_id=$1 AND class_id=$2 AND status='active'`,[studentId,classId]);return !!rows[0];}
async function gradeLocked(studentId,classId){const row=(await pool.query(`SELECT status FROM grade_status WHERE student_id=$1 AND class_id=$2`,[studentId,classId])).rows[0];return row&&['finalized','released'].includes(row.status);}
async function usesDynamicGrading(classId){try{const row=(await pool.query(`SELECT state FROM grading_schemes WHERE class_id=$1`,[classId])).rows[0];return !!row&&['active','finalized'].includes(row.state);}catch(e){if(e&&e.code==='42P01')return false;throw e;}}
async function adjustmentContext(studentId,classId,component){
 const scheme=await getDynamicScheme(classId);
 if(!scheme)return buildAdjustmentContext(studentId,classId,component);
 const c=scheme.components.find(x=>x.component_key===component||x.source_type===component);
 if(!c)return {error:`No active ${component} component exists in this grading scheme.`};
 const max=Number(c.max_points);
 if(!Number.isFinite(max)||max<=0)return {error:`${c.name} Total Required Score must be configured in Weights first.`};
 let recordedTotal=0;
 try {
   const raw=await componentResult(studentId,classId,c);
   // Existing source records are optional for this end-of-semester manual-total workflow.
   // If the source calculator has no configured denominator/records, the component must still appear.
   const sourceMax=Number(raw?.max),sourceEarned=Number(raw?.earned??0);
   recordedTotal=Number.isFinite(sourceMax)&&sourceMax>0?Math.round((sourceEarned/sourceMax)*max*100)/100:0;
 } catch (_) { recordedTotal=0; }
 return {recordedTotal:Math.round(recordedTotal*100)/100,max,label:c.source_type==='attendance'?'days':'points',componentId:c.id,componentName:c.name,componentKey:c.component_key,sourceType:c.source_type};
}
async function adjustmentDelta(studentId,classId,component,newTotal){
 const ctx=await adjustmentContext(studentId,classId,component);
 if(ctx.error)return {valid:false,message:ctx.error};
 if(ctx.needsDenominator)return {valid:false,message:`${ctx.componentName} Overall Total Score is required.`};
 if(typeof newTotal!=='number'||!Number.isFinite(newTotal))return {valid:false,message:'New total must be a number.'};
 if(newTotal<0)return {valid:false,message:'Adjusted total cannot be negative.'};
 if(newTotal>ctx.max)return {valid:false,message:`Adjusted total cannot exceed ${ctx.max} ${ctx.label}.`};
 return {valid:true,deltaPercent:((newTotal-ctx.recordedTotal)/ctx.max)*100,recordedTotal:ctx.recordedTotal,max:ctx.max,newTotal};
}

async function getClassGradebook(classId){
 const {rows:roster}=await pool.query(`SELECT s.id,s.student_number,s.first_name,s.last_name FROM students s JOIN enrollments e ON e.student_id=s.id WHERE e.class_id=$1 AND e.status='active' ORDER BY s.last_name,s.first_name`,[classId]);
 return Promise.all(roster.map(async s=>{const grade=await computeClassGrade(s.id,classId);const comps=grade.components||{};const dynamicComponents=Object.entries(comps).map(([key,c])=>({key,name:c.name||({attendance:'Attendance',quiz:'Quiz',performance:'Performance Task',exam:'Exam'}[key]||key),percent:c.percent,weight:Number(c.weight),available:!!c.available,adjusted:!!c.adjusted,earned:c.earned??null,max:c.max??null}));return {studentId:s.id,studentNumber:s.student_number,studentName:`${s.last_name}, ${s.first_name}`,attendance:comps.attendance?.percent??null,quiz:comps.quiz?.percent??null,performance:comps.performance?.percent??null,exam:comps.exam?.percent??null,components:Object.fromEntries(dynamicComponents.map(c=>[c.key,c])),componentOrder:dynamicComponents.map(c=>c.key),finalGrade:grade.finalGrade,status:grade.status,incompleteReason:grade.message,schemeId:grade.schemeId||null,schemeVersion:grade.schemeVersion||null};}));
}

router.get('/:classId/students/:studentId',async(req,res,next)=>{try{const{classId,studentId}=req.params;if(!checkStudentAccess(req,studentId))return res.status(403).json({error:'You are not authorized to perform this action.'});if(req.user.role==='teacher'){const cls=(await pool.query('SELECT teacher_id FROM classes WHERE id=$1',[classId])).rows[0];if(!cls||cls.teacher_id!==req.user.id)return res.status(403).json({error:'You are not authorized to perform this action.'});}const result=await computeClassGrade(studentId,classId);if(req.user.role==='student'&&result.status!=='released')return res.json({...result,finalGrade:null,visibleToStudent:false});res.json({...result,visibleToStudent:true});}catch(e){next(e);}});
router.get('/:classId',requireClassOwnership,async(req,res,next)=>{try{res.json(await getClassGradebook(req.params.classId));}catch(e){next(e);}});
router.get('/:classId/gradebook',requireClassOwnership,async(req,res,next)=>{try{res.json(await getClassGradebook(req.params.classId));}catch(e){next(e);}});
router.post('/:classId/students/:studentId/finalize',requireRole('teacher','admin'),requireClassOwnership,async(req,res,next)=>{try{const{classId,studentId}=req.params;if(!(await assertEnrolled(studentId,classId)))return res.status(404).json({error:'Student is not actively enrolled in this class.'});const result=await computeClassGrade(studentId,classId);if(!result.complete)return res.status(400).json({error:`Cannot finalize an incomplete grade. ${result.message}`});const prev=(await pool.query('SELECT status FROM grade_status WHERE student_id=$1 AND class_id=$2',[studentId,classId])).rows[0];await pool.query(`INSERT INTO grade_status(student_id,class_id,status,finalized_by,finalized_at) VALUES($1,$2,'finalized',$3,now()) ON CONFLICT(student_id,class_id) DO UPDATE SET status='finalized',finalized_by=excluded.finalized_by,finalized_at=excluded.finalized_at`,[studentId,classId,req.user.id]);await audit(req,{action:'grade_finalization',recordType:'grade_status',recordId:`${studentId}:${classId}`,previousValue:prev,newValue:'finalized'});res.json({message:'Grade finalized.'});}catch(e){next(e);}});
router.post('/:classId/finalize-all',requireRole('teacher','admin'),requireClassOwnership,async(req,res,next)=>{try{const{classId}=req.params;const gradebook=await getClassGradebook(classId);const eligible=gradebook.filter(r=>r.finalGrade!==null&&r.finalGrade!==undefined&&r.status!=='finalized'&&r.status!=='released'&&!r.incompleteReason);const skipped=gradebook.filter(r=>!eligible.includes(r));const finalized=[];for(const row of eligible){const result=await computeClassGrade(row.studentId,classId);if(!result.complete)continue;const prev=(await pool.query('SELECT status FROM grade_status WHERE student_id=$1 AND class_id=$2',[row.studentId,classId])).rows[0];await pool.query(`INSERT INTO grade_status(student_id,class_id,status,finalized_by,finalized_at) VALUES($1,$2,'finalized',$3,now()) ON CONFLICT(student_id,class_id) DO UPDATE SET status='finalized',finalized_by=excluded.finalized_by,finalized_at=excluded.finalized_at`,[row.studentId,classId,req.user.id]);await audit(req,{action:'grade_finalization_bulk',recordType:'grade_status',recordId:`${row.studentId}:${classId}`,previousValue:prev,newValue:'finalized'});finalized.push(row.studentId);}res.json({message:`${finalized.length} grade${finalized.length===1?'':'s'} finalized. ${skipped.length} skipped because they are incomplete or already finalized/released.`,finalizedCount:finalized.length,skippedCount:skipped.length});}catch(e){next(e);}});
router.post('/:classId/students/:studentId/release',requireRole('teacher','admin'),requireClassOwnership,async(req,res,next)=>{try{const{classId,studentId}=req.params;const status=(await pool.query('SELECT status FROM grade_status WHERE student_id=$1 AND class_id=$2',[studentId,classId])).rows[0];if(!status||status.status!=='finalized')return res.status(400).json({error:'Grade must be finalized before it can be released.'});await pool.query(`UPDATE grade_status SET status='released',released_at=now() WHERE student_id=$1 AND class_id=$2`,[studentId,classId]);await audit(req,{action:'grade_release',recordType:'grade_status',recordId:`${studentId}:${classId}`});res.json({message:'Grade released to student.'});}catch(e){next(e);}});
router.get('/:classId/unfinalize-requests',requireRole('teacher','admin'),requireClassOwnership,async(req,res,next)=>{try{const{classId}=req.params;const params=[classId];let teacherClause='';if(req.user.role==='teacher'){params.push(req.user.id);teacherClause=' AND r.teacher_id=$2';}const{rows}=await pool.query(`SELECT r.*,s.first_name,s.last_name,s.student_number FROM grade_unfinalize_requests r JOIN students s ON s.id=r.student_id WHERE r.class_id=$1${teacherClause} ORDER BY CASE r.status WHEN 'pending' THEN 0 ELSE 1 END,r.requested_at DESC`,params);res.json(rows);}catch(e){next(e);}});
router.post('/:classId/students/:studentId/request-unfinalize',requireRole('teacher'),requireClassOwnership,async(req,res,next)=>{try{const{classId,studentId}=req.params;const reason=String(req.body.reason||'').trim();if(reason.length<5)return res.status(400).json({error:'Please provide a reason of at least 5 characters.'});if(!(await assertEnrolled(studentId,classId)))return res.status(404).json({error:'Student is not actively enrolled in this class.'});const gs=(await pool.query('SELECT status FROM grade_status WHERE student_id=$1 AND class_id=$2',[studentId,classId])).rows[0];if(!gs||!['finalized','released'].includes(gs.status))return res.status(409).json({error:'Only finalized or released grades can be requested for unfinalization.'});const existing=(await pool.query(`SELECT id FROM grade_unfinalize_requests WHERE class_id=$1 AND student_id=$2 AND status='pending'`,[classId,studentId])).rows[0];if(existing)return res.status(409).json({error:'An unfinalize request for this learner is already pending administrator review.'});const id=crypto.randomUUID();await pool.query(`INSERT INTO grade_unfinalize_requests(id,class_id,student_id,teacher_id,requested_status,reason) VALUES($1,$2,$3,$4,$5,$6)`,[id,classId,studentId,req.user.id,gs.status,reason]);await audit(req,{action:'grade_unfinalize_requested',recordType:'grade_unfinalize_request',recordId:id,previousValue:gs.status,newValue:{status:'pending',reason}});res.status(201).json({id,status:'pending',message:'Unfinalize request submitted to the administrator.'});}catch(e){if(e.code==='23505')return res.status(409).json({error:'An unfinalize request for this learner is already pending administrator review.'});next(e);}});

router.post('/:classId/students/:studentId/reopen',requireRole('admin'),async(req,res,next)=>{try{const{classId,studentId}=req.params;const prev=(await pool.query('SELECT status FROM grade_status WHERE student_id=$1 AND class_id=$2',[studentId,classId])).rows[0];await pool.query(`UPDATE grade_status SET status='in_progress',finalized_by=NULL,finalized_at=NULL,released_at=NULL WHERE student_id=$1 AND class_id=$2`,[studentId,classId]);await audit(req,{action:'grade_reopen',recordType:'grade_status',recordId:`${studentId}:${classId}`,previousValue:prev,newValue:'in_progress'});res.json({message:'Grade reopened.'});}catch(e){next(e);}});

router.get('/:classId/students/:studentId/adjustments',requireRole('teacher','admin'),requireClassOwnership,async(req,res,next)=>{try{const{classId,studentId}=req.params;if(!(await assertEnrolled(studentId,classId)))return res.status(404).json({error:'Student is not actively enrolled in this class.'});const {rows:existing}=await pool.query(`SELECT * FROM grade_adjustments WHERE student_id=$1 AND class_id=$2`,[studentId,classId]);const byComponent={};for(const r of existing)byComponent[r.component]=r;const result={};const scheme=await getDynamicScheme(classId);const adjustmentComponents=scheme?scheme.components.map(x=>x.component_key):VALID_COMPONENTS;for(const component of adjustmentComponents){const ctx=await adjustmentContext(studentId,classId,component),a=byComponent[component];result[component]=ctx.error?{available:false,message:ctx.error}:ctx.needsDenominator?{available:true,needsDenominator:true,recordedTotal:ctx.recordedTotal,label:ctx.label,componentId:ctx.componentId,componentName:ctx.componentName,currentAdjustmentPoints:0,currentTotal:ctx.recordedTotal}:{available:true,recordedTotal:ctx.recordedTotal,max:ctx.max,label:ctx.label,componentId:ctx.componentId,componentName:ctx.componentName,currentAdjustmentPoints:a?Number(a.adjustment_points):0,currentTotal:a?Math.round((ctx.recordedTotal+(Number(a.adjustment_points)/100)*ctx.max)*100)/100:ctx.recordedTotal};}res.json(result);}catch(e){next(e);}});
router.put('/:classId/students/:studentId/adjustments/:component',requireRole('teacher','admin'),requireClassOwnership,async(req,res,next)=>{try{const{classId,studentId,component}=req.params;const scheme=await getDynamicScheme(classId);const validComponent=scheme?scheme.components.some(x=>x.component_key===component):VALID_COMPONENTS.includes(component);if(!validComponent)return res.status(400).json({error:'Invalid component.'});if(!(await assertEnrolled(studentId,classId)))return res.status(404).json({error:'Student is not actively enrolled in this class.'});if(await gradeLocked(studentId,classId))return res.status(409).json({error:'Finalized or released grades cannot be adjusted. An administrator must reopen the grade first.'});const reason=String(req.body.reason||'').trim();if(reason.length<5)return res.status(400).json({error:'Please provide an adjustment reason of at least 5 characters.'});const result=await adjustmentDelta(studentId,classId,component,Number(req.body.newTotal));if(!result.valid)return res.status(400).json({error:result.message});const existing=(await pool.query('SELECT * FROM grade_adjustments WHERE student_id=$1 AND class_id=$2 AND component=$3',[studentId,classId,component])).rows[0];const id=existing?.id||crypto.randomUUID();await pool.query(`INSERT INTO grade_adjustments(id,student_id,class_id,component,adjustment_points,reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(student_id,class_id,component) DO UPDATE SET adjustment_points=excluded.adjustment_points,reason=excluded.reason,created_by=excluded.created_by,updated_at=now()`,[id,studentId,classId,component,result.deltaPercent,reason,req.user.id]);await audit(req,{action:'manual_total_adjustment',recordType:`grade_adjustment_${component}`,recordId:`${studentId}:${classId}`,previousValue:existing||null,newValue:{...result,reason:reason}});res.json({message:`${component[0].toUpperCase()+component.slice(1)} total adjusted to ${result.newTotal} / ${result.max}.`});}catch(e){next(e);}});
router.delete('/:classId/students/:studentId/adjustments/:component',requireRole('teacher','admin'),requireClassOwnership,async(req,res,next)=>{try{const{classId,studentId,component}=req.params;if(!VALID_COMPONENTS.includes(component))return res.status(400).json({error:'Invalid component.'});if(!(await assertEnrolled(studentId,classId)))return res.status(404).json({error:'Student is not actively enrolled in this class.'});if(await gradeLocked(studentId,classId))return res.status(409).json({error:'Finalized or released grades cannot be adjusted. An administrator must reopen the grade first.'});const prev=(await pool.query(`DELETE FROM grade_adjustments WHERE student_id=$1 AND class_id=$2 AND component=$3 RETURNING *`,[studentId,classId,component])).rows[0];if(!prev)return res.status(404).json({error:'No adjustment exists for this component.'});await audit(req,{action:'manual_total_adjustment_removed',recordType:`grade_adjustment_${component}`,recordId:`${studentId}:${classId}`,previousValue:{adjustmentPoints:Number(prev.adjustment_points)},newValue:null});res.json({message:`${component[0].toUpperCase()+component.slice(1)} adjustment removed — reverted to the original computed total.`});}catch(e){next(e);}});
module.exports=router;